server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka.registry7001.com:7001/eureka,http://eureka.registry7002.com:7002/eureka,http://eureka.registry7003.com:7003/eureka
    register-with-eureka: false