server:
  port: 8001
  display-name: dept

mybatis:
  config-location: classpath:mybatis/mybatis.xml        # mybatis配置文件所在路径
  type-aliases-package: com.yzz.cloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: springcloudservice-dept
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.1.80:3306/cloudDB01              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200   # 等待连接获取的最大超时时间

eureka:
  client:
    service-url:
      defaultZone: http://eureka.registry7001.com:7011/eureka,http://eureka.registry7002.com:7022/eureka,http://eureka.registry7003.com:7033/eureka
  instance:
    instance-id: springcloudservice-provider-dept-8001
    prefer-ip-address: true

info:
  app.name: springcloudservice-provider-dept-8001
  company: www.yzz.io
management:
  security:
    enabled: false








